name: Build and Push FBIMostWanted Docker Image to ACR

on:
  push:
    paths:
      - 'MCPServers/FBIMostWanted/**'
      - '.github/workflows/docker-publish-fbimostwanted.yml'
      - 'Infrastructure/containerApp-FBIMostWanted.bicepparam'
    branches:
      - main
  workflow_dispatch:

jobs:
  call-docker-publish:
    uses: ./.github/workflows/docker-publish-template.yml
    with:
      mcp_server: 'FBIMostWanted'
      image_name: 'fbimostwanted'
      docker_context: 'MCPServers'
    secrets: inherit

  deploy-container-app:
    needs: call-docker-publish
    uses: ./.github/workflows/docker-deploy-containerapp-template.yml
    with:
      parameter_file_name: containerApp-FBIMostWanted.bicepparam
    secrets: inherit
